<!--
var jerarquia = [
	["Ministerio de Agricultura","minagri",[
		["Fundación de Comunicaciones y Cultura del Agro",""],
		["Instituto de Investigaciones Agropecuarias","Inia"],
		["Fondo de Investigación Agropecuaria","Fia"],
		["Instituto Forestal","Infor"],
		["Subsecretaría de Agricultura",""],
		["--Oficina de Estudios y Políticas Agrarias","Odepa"],
		["--Instituto de Desarrollo Agropecuario","Indap"],
		["--Corporación Nacional Forestal","Conaf"],
		["--Servicio Agrícola y Ganadero","Sag"],
		["--Comisión Nacional de Riego","CNR"]
	]],
	["Ministerio de Bienes Nacionales","minbienes",[
		["División de Planificación y Presupuesto",""],
		["Subsecretaría de Bienes Nacionales",""],
		["--División Administrativa",""],
		["--División de Bienes Nacionales",""],
		["--División de Catastro",""],
		["--División de Constitución de Propiedades Raíz",""],
		["--División Jurídica",""]
	]],
	["Ministerio de Defensa Nacional","defensa",[
		["Estado Mayor de la Defensa Nacional",""],
		["Ejército de Chile",""],
		["Armada de Chile",""],
		["Fuerza Aérea de Chile","Fach"],
		["Subsecretaría de Guerra",""],
		["--Defensa Civil de Chile",""],
		["--Dirección General de Movilización Nacional",""],
		["--Academia Nacional de Estudios Políticos y Estratégicos",""],
		["--Instituto Geográfico Militar",""],
		["--Fábricas y Maestranzas del Ejército","Famae"],
		["--Obispado Castrense de Chile",""],
		["--Cuerpo de Veteranos de la Guerra del Pacífico",""],
		["--Ministerio Público Militar",""],
		["Subsecretaría de Marina",""],
		["--Astilleros y Maestranzas de la Armada","Asmar"],
		["--Servicio Hidrográfico y Oceanográfico de la Armada de Chile","Shoa"],
		["--Dirección General del Territorio Marítimo y Marina Mercante","Directemar"],
		["Subsecretaría de Aviación",""],
		["--Empresa Nacional Aeronáutica de Chile","Enaer"],
		["--Servicio Aerofotogramétrico de la Fuerza Aérea de Chile",""],
		["--Dirección General de Aeronáutica Civil",""],
		["Subsecretaría de Carabineros",""],
		["--Carabineros de Chile",""],
		["Subsecretaría de Investigaciones",""],
		["--Policía de Investigaciones de Chile",""]
	]],
	["Ministerio de Economía","economia",[
		["Servicio Nacional de Pesca","Sernapesca"],
		["Subsecretaría de Economía",""],
		["--Estudios Económicos",""],
		["--Asesoría Jurídica",""],
		["--Política Comercial e Industrial",""],
		["--Departamento de Propiedad Industrial","Dpi"],
		["--Comercio Exterior",""],
		["--Cooperativas",""],
		["--Servicio Nacional del Consumidor","Sernac"],
		["--Fiscalía Nacional Económica","Fne"],
		["--Instituto Nacional de Estadísticas","Ine"],
		["--Servicio Nacional de Turismo","Sernatur"],
		["--Comisión Nacional de Riego","Conar"],
		["--Superintendencia de Electricidad y Combustibles","Sec"],
		["--Corporación de Fomento de la Producción","Corfo"],
		["----Comité Sistema de Empresas Públicas","SEP"],
		["Subsecretaría de Pesca","Subpesca"],
		["--Departamento de Difusión y Cooperación Pesquera",""],
		["--División Jurídica",""],
		["--División Administración Pesquera",""],
		["--División de Desarrollo Pesquero",""],
		["--Departamento Administrativo",""],
		["Comité de Inversiones Extranjeras","cinver"],
		["Servicio de Cooperación Técnica","sercotec"]
	]],
	["Ministerio de Educación","mineduc",[
		["Subsecretaría de Educación",""],
		["--Dirección de Bibliotecas, Archivos y Museos","Dibam"],
		["--División de Educación General",""],
		["--Departamento Administrativo General",""],
		["--División de Educación Superior",""],
		["--División de Cultura",""],
		["--Departamento Jurídico",""],
		["--División de Planificación y Presupuesto",""],
		["--Centro de Perfeccionamiento, Experimentación e Investigaciones Pedagógicas",""],
		["--Comisión Nacional de Investigación Científica y Tecnológica","Conicyt"],
		["--Junta Nacional de Auxilio Escolar y Becas","Junaeb"],
		["--Junta Nacional de Jardines Infantiles","Junji"],
		["--Consejo de Rectores",""],
		["--Consejo Superior de Educación",""]
	]],
	["Ministerio de Hacienda","minhacienda",[
		["Subsecretaría de Hacienda",""],
		["--Servicio de Impuestos Internos","Sii"],
		["--Dirección de Presupuestos","Dipres"],
		["--Tesorería General de la República","Tgr"],
		["--Servicio Nacional de Aduanas","Aduanas"],
		["--Superintendencia de Valores y Seguros","Svs"],
		["--Dirección de Compras y Contratación Pública","ChileCompra"],
		["--Superintendencia de Casinos de Juego","SCJ"],
		["--Casa de Moneda de Chile",""],
		["--Dirección Nacional del Servicio Civil","Dnsc"],
		["--Superintendencia de Bancos e Instituciones Financieras","Sbif"]
	]],
	["Ministerio de Justicia","minjusticia",[
		["Gendarmería de Chile","Gendarmeria"],
		["Servicio Nacional de Menores","Sename"],
		["Servicio Médico Legal","Sml"],
		["Oficina de Planificación y Presupuesto",""],
		["Servicio de Registro Civil e Identificación","Srcei"],
		["Fiscalía Nacional de Quiebras",""],
		["Corporación de Asistencia Judicial","Caj"],
		["Defensoría Penal Pública","DPP"],
		["Subsecretaría de Justicia",""],
		["--División Judicial",""],
		["--División Jurídica",""],
		["--División Defensa Social",""],
		["--Departamento Administrativo",""]
	]],
	["Ministerio del Interior","interior",[
		["Oficina Nacional de Emergencia","Onemi"],
		["Servicio Electoral","Servel"],
		["Gobierno Regional de Tarapaca","goretarapaca"],
		["Gobierno Regional de Antofagasta","goreantof"],
		["Gobierno Regional de Atacama","goreatacama"],
		["Gobierno Regional de Coquimbo","gorecoquimbo"],
		["Gobierno Regional de Valparaíso","gorevalpo"],
		["Gobierno Regional Libertador Bernardo O'Higgins","goreohiggins"],
		["Gobierno Regional del Maule","goremaule"],
		["Gobierno Regional del Bío-Bío","gorebiobio"],
		["Gobierno Regional de la Araucanía","gorearaucania"],
		["Gobierno Regional de los Lagos","gorelagos"],
		["Gobierno Regional de Aysén","Undécima Región"],
		["Gobierno Regional de Magallanes","Duodécima Región"],
		["Gobierno Regional de Santiago","goresantiago"],
		["Subsecretaría del Interior","Subinterior"],
		["--División de Seguridad y Participación Ciudadana",""],
		["--División Informática",""],
		["--División Jurídica",""],
		["--División Gobierno Interior",""],
		["--División Económica",""],
		["Subsecretaría de Desarrollo Regional y Administrativo","Subdere"],
		["--División Políticas de Regionalización y Descentralización",""],
		["--División Apoyo Administrativo",""],
		["--División Fortalecimiento Institucional y Financiero",""],
		["--División Evaluación y Cuentas Públicas de la Descentralización",""]
	]],
	["Ministerio del Trabajo y Previsión Social","mintrab",[
		["Subsecretaría del Trabajo",""],
		["--Oficina Jurídica",""],
		["--Departamento Administrativo",""],
		["--Oficina de Organización Laboral e Internacional",""],
		["--Oficina de Relaciones Públicas",""],
		["--Dirección del Trabajo",""],
		["--Servicio Nacional de Capacitación y Empleo","Sence"],
		["--Dirección General de Crédito Prendario","Dicrep"],
		["Subsecretaría de Previsión Social",""],
		["--Oficina Jurídica",""],
		["--Departamento Administrativo",""],
		["--Superintendencia de Seguridad Social",""],
		["--Superintendencia de Administradoras de Fondos de Pensiones","Safp"],
		["--Instituto de Normalización Previsional","Inp"],
		["--Dirección de Previsión de Carabineros","Dipreca"],
		["--Caja de Previsión de la Defensa Nacional","Capredena"]
	]],
	["Ministerio de Minería","mineria",[
		["Subsecretaría de Minería",""],
		["--Empresa Nacional de Minería",""],
		["--Corporación Nacional del Cobre de Chile",""],
		["--Empresa Nacional del Petróleo","Enap"],
		["--Comisión Chilena de Energía Nuclear","Cchen"],
		["--Servicio Nacional de Geología y Minería","Sernageomin"],
		["--Comisión Chilena del Cobre","Cochilco"],
		["--División de Administración y Finanzas",""],
		["--División Jurídica",""],
		["--División de Planificación y Desarrollo",""]
	]],
	["Ministerio de Obras Públicas","mop",[
		["Subsecretaría de Obras Públicas",""],
		["--Dirección General de Obras Públicas","Dgop"],
		["----Dirección de Contabilidad y Finanzas",""],
		["----Dirección de Planeamiento",""],
		["----Fiscalía",""],
		["----Dirección de Arquitectura",""],
		["----Dirección de Vialidad",""],
		["----Dirección de Obras Portuarias",""],
		["----Dirección de Obras Hidráulicas",""],
		["----Dirección de Aeropuertos",""],
		["----Coordinación General de Concesiones",""],
		["--Superintendencia de Servicios Sanitarios","Sss"],
		["--Instituto Nacional de Hidráulica","Inh"],
		["--Dirección General de Aguas",""],
		["--Comité de Agua Potable Rural",""]
	]],
	["Ministerio de Planificación y Cooperación","mideplan",[
		["Subsecretaría de Planificación y Cooperación",""],
		["--División de Planificación Regional",""],
		["--División de Planificación, Estudio e Inversiones",""],
		["--División Jurídica",""],
		["--División Social",""],
		["--División de Administración y Finanzas",""],
		["--Programa de Vialidad y Transporte Urbano","Sectra"],
		["--Fondo Nacional de la Discapacidad","Fonadis"],
		["--Agencia de Cooperación Internacional","Agci"],
		["--Fondo de Solidaridad e Inversión Social","Fosis"],
		["--Servicio Nacional de la Mujer (#)","Sernam"],
		["--Instituto Nacional de la Juventud","Injuv"],
		["--Corporación Nacional de Desarrollo Indígena","Conadi"]
	]],
	["Ministerio de Relaciones Exteriores","minrel",[
		["Dirección General de Relaciones Económicas Internacionales","Direcon"],
		["Dirección Nacional de Fronteras y Límites del Estado","Difrol"],
		["Instituto Antártico Chileno","Inarch"],
		["Subsecretaría de Relaciones Exteriores",""],
		["--Academia Diplomática de Chile",""],
		["--Dirección de Asuntos Culturales",""],
		["--Dirección General de Política Exterior",""],
		["--Dirección General Administrativa",""],
		["--Dirección General de Asuntos Consulares e Inmigración",""],
		["--Dirección General de Relaciones Económicas Internacionales",""],
		["--Dirección de Chilenos en el Exterior",""],
		["--Auditoría Ministerial",""],
		["--Dirección de Coordinación Regional",""],
		["--Dirección de Derechos Humanos",""]
	]],
	["Ministerio de Salud","minsal",[
		["Subsecretaría de Salud",""],
		["--División de Recursos Humanos",""],
		["--División de Atención Primaria",""],
		["--División de Inversiones y Desarrollo de Red Asistencial",""],
		["--División de Presupuesto y Administración",""],
		["--División de Salud Ambiental",""],
		["--División de Salud de las Personas",""],
		["--Departamento de Asesoría Jurídica",""],
		["--Comisión Médica de Reclamos",""],
		["--Oficina de Emergencias y Catástrofes",""],
		["--Comisión Nacional del SIDA",""],
		["--Unidad de Gestión de Servicios",""],
		["--Servicios de Salud",""],
		["--Instituto de Salud Pública","Isp"],
		["--Fondo Nacional de Salud","Fonasa"],
		["--Central de Abastecimiento","Cenabast"],
		["--Superintendencia de Salud",""]
	]],
	["Ministerio de Transportes y Telecomunicaciones","mtt",[
		["Subsecretaría de Transportes",""],
		["--Relaciones Públicas",""],
		["--Departamento Legal",""],
		["--División de Administración y Finanzas",""],
		["----Departamento Administrativo",""],
		["----Departamento de Coordinación y Gestión",""],
		["----Oficina de Presupuesto",""],
		["----Servicio de Bienestar",""],
		["--División de Operaciones",""],
		["----Departamento de Fiscalización",""],
		["----Departamento Marítimo, Fluvial y Lacustre",""],
		["----Departamento de Transporte Terrestre",""],
		["----Oficina Nacional de Asuntos Internacionales",""],
		["----Centro de Control y Certificación Vehicular",""],
		["--División de Planificación Estratégica",""],
		["Subsecretaría de Telecomunicaciones",""],
		["--Departamento de Planificación y Control de Gestión",""],
		["--Departamento Internacional",""],
		["--División de Concesiones",""],
		["----Departamento de Radiodifusión",""],
		["----Departamento de Servicios Limitados",""],
		["----Departamento de Servicios Públicos",""],
		["----Departamento de Administración de Frecuencias",""],
		["--División de Fiscalización",""],
		["----Departamento de Control del Espectro Radioeléctrico",""],
		["----Departamento de Atención a los Consumidores",""],
		["----Departamento de Supervisión de Redes y Servicios",""],
		["--División Política Regulatoria y Estudios",""],
		["----Departamento de Ingeniería y Administración del Espectro Radioeléctrico",""],
		["----Departamento de Regulación Económica",""],
		["----Departamento de Acceso Universal",""],
		["--División de Administración y Finanzas",""],
		["----Departamento de Adquisiciones e Inventario",""],
		["----Departamento de Recursos Humanos",""],
		["----Departamento de Finanzas",""],
		["----Departamento de Informática",""],
		["--División Jurídica",""],
		["----Departamento de Reglamentos",""],
		["--Junta de Aeronaútica Civil","JAC"]
	]],
	["Ministerio de Vivienda y Urbanismo","minvu",[
		["Comité de Planificación y Coordinación",""],
		["Subsecretaría de Vivienda y Urbanismo",""],
		["--Departamento de Comunicaciones",""],
		["--Auditoría Interna Ministerial",""],
		["--Consejo Directivo Servicio de Bienestar",""],
		["--Contraloría Interna Ministerial",""],
		["--Oficina de Información y Difusión al Usuario",""],
		["--División de Desarrollo Urbano",""],
		["--División de Política Habitacional",""],
		["--División de Finanzas",""],
		["--División Jurídica",""],
		["----Servicios de Vivienda y Urbanización",""],
		["----Servicio Metropolitano de Vivienda y Urbanización",""],
		["----Parque Metropolitano",""],
		["--División Técnica de Estudios y Fomento Habitacional",""],
		["--División Administrativa",""],
		["--División de Informática",""]
	]],
	["Ministerio Secretaría General de Gobierno","segegob",[
		["Consejo Nacional de Televisión",""],
		["Instituto Nacional de Deportes de Chile",""],
		["Subsecretaría General de Gobierno",""],
		["--Unidad Jurídica",""],
		["--Unidad de Planificación",""],
		["--División de Organizaciones Sociales","Dos"],
		["--División Secretaría de Comunicación y Cultura",""],
		["--División de Administración Y Finanzas",""]
	]],
	["Ministerio Secretaría General de la Presidencia","minsegpres",[
		["Subsecretaría General de la Presidencia",""],
		["--División Relaciones Políticas e Institucionales",""],
		["--División de Coordinación Interministerial",""],
		["--Proyecto de Reforma y Modernización del Estado","Pryme"],
		["--División Jurídico-Legislativa",""],
		["--División Estudios",""],
		["--División Administración General",""],
		["Consejo de Auditoría Interna de Gobierno","Caig"],
		["Comisión Nacional del Medio Ambiente","Conama"],
		["Servicio Nacional del Adulto Mayor","Senama"]
	]],
	["Presidencia de la República","Presidencia",[['']]],
	["Contraloría General de la República","CGR",[['']]],
	["Comisión Nacional de Energía","CNE",[['']]],
	["Consejo Nacional de la Cultura y de las Artes","CNCA",[['']]]
	];

function cargaMinisterios()
{
	var m = document.form.fMinisterio;
	for (i=0; i<jerarquia.length; i++)
		m.options[m.options.length] = new Option(jerarquia[i][0],jerarquia[i][0]);
}

function cargaInstituciones(num)
{
	var m = document.form.fInstitucion;
	for (i=m.options.length-1; i>=0; i--)
		m.options[i] = null;
	for (i=0; i<jerarquia[num][2].length; i++)
		m.options[m.options.length] = new Option(jerarquia[num][2][i][0],jerarquia[num][2][i][0]);
}
-->
